# Generated by Django 5.0.2 on 2024-03-10 21:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0004_alter_temporaryuser_group'),
    ]

    operations = [
        migrations.AlterField(
            model_name='temporaryuser',
            name='last_name',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
